/*
 * Vies on-the-Web Endpoint
 * This is the contract for Vies on-the-Web endpoints. The checkVat service supports exact and approximate matching at the same time. In order to retrieve the requestIdentifier, the information about requesterMemberStateCode and requesterNumber have to be provided.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.vies.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.vies.api.client.invoker.JSON;

/**
 * CheckVatRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CheckVatRequest {
  public static final String SERIALIZED_NAME_COUNTRY_CODE = "countryCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  @javax.annotation.Nullable
  private String countryCode;

  public static final String SERIALIZED_NAME_VAT_NUMBER = "vatNumber";
  @SerializedName(SERIALIZED_NAME_VAT_NUMBER)
  @javax.annotation.Nullable
  private String vatNumber;

  public static final String SERIALIZED_NAME_REQUESTER_MEMBER_STATE_CODE = "requesterMemberStateCode";
  @SerializedName(SERIALIZED_NAME_REQUESTER_MEMBER_STATE_CODE)
  @javax.annotation.Nullable
  private String requesterMemberStateCode;

  public static final String SERIALIZED_NAME_REQUESTER_NUMBER = "requesterNumber";
  @SerializedName(SERIALIZED_NAME_REQUESTER_NUMBER)
  @javax.annotation.Nullable
  private String requesterNumber;

  public static final String SERIALIZED_NAME_TRADER_NAME = "traderName";
  @SerializedName(SERIALIZED_NAME_TRADER_NAME)
  @javax.annotation.Nullable
  private String traderName;

  public static final String SERIALIZED_NAME_TRADER_STREET = "traderStreet";
  @SerializedName(SERIALIZED_NAME_TRADER_STREET)
  @javax.annotation.Nullable
  private String traderStreet;

  public static final String SERIALIZED_NAME_TRADER_POSTAL_CODE = "traderPostalCode";
  @SerializedName(SERIALIZED_NAME_TRADER_POSTAL_CODE)
  @javax.annotation.Nullable
  private String traderPostalCode;

  public static final String SERIALIZED_NAME_TRADER_CITY = "traderCity";
  @SerializedName(SERIALIZED_NAME_TRADER_CITY)
  @javax.annotation.Nullable
  private String traderCity;

  public static final String SERIALIZED_NAME_TRADER_COMPANY_TYPE = "traderCompanyType";
  @SerializedName(SERIALIZED_NAME_TRADER_COMPANY_TYPE)
  @javax.annotation.Nullable
  private String traderCompanyType;

  public CheckVatRequest() {
  }

  public CheckVatRequest countryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * Get countryCode
   * @return countryCode
   */
  @javax.annotation.Nullable
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
  }


  public CheckVatRequest vatNumber(@javax.annotation.Nullable String vatNumber) {
    this.vatNumber = vatNumber;
    return this;
  }

  /**
   * Get vatNumber
   * @return vatNumber
   */
  @javax.annotation.Nullable
  public String getVatNumber() {
    return vatNumber;
  }

  public void setVatNumber(@javax.annotation.Nullable String vatNumber) {
    this.vatNumber = vatNumber;
  }


  public CheckVatRequest requesterMemberStateCode(@javax.annotation.Nullable String requesterMemberStateCode) {
    this.requesterMemberStateCode = requesterMemberStateCode;
    return this;
  }

  /**
   * Get requesterMemberStateCode
   * @return requesterMemberStateCode
   */
  @javax.annotation.Nullable
  public String getRequesterMemberStateCode() {
    return requesterMemberStateCode;
  }

  public void setRequesterMemberStateCode(@javax.annotation.Nullable String requesterMemberStateCode) {
    this.requesterMemberStateCode = requesterMemberStateCode;
  }


  public CheckVatRequest requesterNumber(@javax.annotation.Nullable String requesterNumber) {
    this.requesterNumber = requesterNumber;
    return this;
  }

  /**
   * Get requesterNumber
   * @return requesterNumber
   */
  @javax.annotation.Nullable
  public String getRequesterNumber() {
    return requesterNumber;
  }

  public void setRequesterNumber(@javax.annotation.Nullable String requesterNumber) {
    this.requesterNumber = requesterNumber;
  }


  public CheckVatRequest traderName(@javax.annotation.Nullable String traderName) {
    this.traderName = traderName;
    return this;
  }

  /**
   * Get traderName
   * @return traderName
   */
  @javax.annotation.Nullable
  public String getTraderName() {
    return traderName;
  }

  public void setTraderName(@javax.annotation.Nullable String traderName) {
    this.traderName = traderName;
  }


  public CheckVatRequest traderStreet(@javax.annotation.Nullable String traderStreet) {
    this.traderStreet = traderStreet;
    return this;
  }

  /**
   * Get traderStreet
   * @return traderStreet
   */
  @javax.annotation.Nullable
  public String getTraderStreet() {
    return traderStreet;
  }

  public void setTraderStreet(@javax.annotation.Nullable String traderStreet) {
    this.traderStreet = traderStreet;
  }


  public CheckVatRequest traderPostalCode(@javax.annotation.Nullable String traderPostalCode) {
    this.traderPostalCode = traderPostalCode;
    return this;
  }

  /**
   * Get traderPostalCode
   * @return traderPostalCode
   */
  @javax.annotation.Nullable
  public String getTraderPostalCode() {
    return traderPostalCode;
  }

  public void setTraderPostalCode(@javax.annotation.Nullable String traderPostalCode) {
    this.traderPostalCode = traderPostalCode;
  }


  public CheckVatRequest traderCity(@javax.annotation.Nullable String traderCity) {
    this.traderCity = traderCity;
    return this;
  }

  /**
   * Get traderCity
   * @return traderCity
   */
  @javax.annotation.Nullable
  public String getTraderCity() {
    return traderCity;
  }

  public void setTraderCity(@javax.annotation.Nullable String traderCity) {
    this.traderCity = traderCity;
  }


  public CheckVatRequest traderCompanyType(@javax.annotation.Nullable String traderCompanyType) {
    this.traderCompanyType = traderCompanyType;
    return this;
  }

  /**
   * Get traderCompanyType
   * @return traderCompanyType
   */
  @javax.annotation.Nullable
  public String getTraderCompanyType() {
    return traderCompanyType;
  }

  public void setTraderCompanyType(@javax.annotation.Nullable String traderCompanyType) {
    this.traderCompanyType = traderCompanyType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckVatRequest checkVatRequest = (CheckVatRequest) o;
    return Objects.equals(this.countryCode, checkVatRequest.countryCode) &&
        Objects.equals(this.vatNumber, checkVatRequest.vatNumber) &&
        Objects.equals(this.requesterMemberStateCode, checkVatRequest.requesterMemberStateCode) &&
        Objects.equals(this.requesterNumber, checkVatRequest.requesterNumber) &&
        Objects.equals(this.traderName, checkVatRequest.traderName) &&
        Objects.equals(this.traderStreet, checkVatRequest.traderStreet) &&
        Objects.equals(this.traderPostalCode, checkVatRequest.traderPostalCode) &&
        Objects.equals(this.traderCity, checkVatRequest.traderCity) &&
        Objects.equals(this.traderCompanyType, checkVatRequest.traderCompanyType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, vatNumber, requesterMemberStateCode, requesterNumber, traderName, traderStreet, traderPostalCode, traderCity, traderCompanyType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckVatRequest {\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    vatNumber: ").append(toIndentedString(vatNumber)).append("\n");
    sb.append("    requesterMemberStateCode: ").append(toIndentedString(requesterMemberStateCode)).append("\n");
    sb.append("    requesterNumber: ").append(toIndentedString(requesterNumber)).append("\n");
    sb.append("    traderName: ").append(toIndentedString(traderName)).append("\n");
    sb.append("    traderStreet: ").append(toIndentedString(traderStreet)).append("\n");
    sb.append("    traderPostalCode: ").append(toIndentedString(traderPostalCode)).append("\n");
    sb.append("    traderCity: ").append(toIndentedString(traderCity)).append("\n");
    sb.append("    traderCompanyType: ").append(toIndentedString(traderCompanyType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("countryCode");
    openapiFields.add("vatNumber");
    openapiFields.add("requesterMemberStateCode");
    openapiFields.add("requesterNumber");
    openapiFields.add("traderName");
    openapiFields.add("traderStreet");
    openapiFields.add("traderPostalCode");
    openapiFields.add("traderCity");
    openapiFields.add("traderCompanyType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CheckVatRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CheckVatRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CheckVatRequest is not found in the empty JSON string", CheckVatRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CheckVatRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CheckVatRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("countryCode") != null && !jsonObj.get("countryCode").isJsonNull()) && !jsonObj.get("countryCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `countryCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("countryCode").toString()));
      }
      if ((jsonObj.get("vatNumber") != null && !jsonObj.get("vatNumber").isJsonNull()) && !jsonObj.get("vatNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vatNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vatNumber").toString()));
      }
      if ((jsonObj.get("requesterMemberStateCode") != null && !jsonObj.get("requesterMemberStateCode").isJsonNull()) && !jsonObj.get("requesterMemberStateCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requesterMemberStateCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requesterMemberStateCode").toString()));
      }
      if ((jsonObj.get("requesterNumber") != null && !jsonObj.get("requesterNumber").isJsonNull()) && !jsonObj.get("requesterNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requesterNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requesterNumber").toString()));
      }
      if ((jsonObj.get("traderName") != null && !jsonObj.get("traderName").isJsonNull()) && !jsonObj.get("traderName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traderName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traderName").toString()));
      }
      if ((jsonObj.get("traderStreet") != null && !jsonObj.get("traderStreet").isJsonNull()) && !jsonObj.get("traderStreet").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traderStreet` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traderStreet").toString()));
      }
      if ((jsonObj.get("traderPostalCode") != null && !jsonObj.get("traderPostalCode").isJsonNull()) && !jsonObj.get("traderPostalCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traderPostalCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traderPostalCode").toString()));
      }
      if ((jsonObj.get("traderCity") != null && !jsonObj.get("traderCity").isJsonNull()) && !jsonObj.get("traderCity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traderCity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traderCity").toString()));
      }
      if ((jsonObj.get("traderCompanyType") != null && !jsonObj.get("traderCompanyType").isJsonNull()) && !jsonObj.get("traderCompanyType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traderCompanyType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traderCompanyType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CheckVatRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CheckVatRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CheckVatRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CheckVatRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CheckVatRequest>() {
           @Override
           public void write(JsonWriter out, CheckVatRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CheckVatRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CheckVatRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CheckVatRequest
   * @throws IOException if the JSON string is invalid with respect to CheckVatRequest
   */
  public static CheckVatRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CheckVatRequest.class);
  }

  /**
   * Convert an instance of CheckVatRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

