/*
 * Vies on-the-Web Endpoint
 * This is the contract for Vies on-the-Web endpoints. The checkVat service supports exact and approximate matching at the same time. In order to retrieve the requestIdentifier, the information about requesterMemberStateCode and requesterNumber have to be provided.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.vies.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import pl.wtx.vies.api.client.model.Match;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.vies.api.client.invoker.JSON;

/**
 * CheckVatResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CheckVatResponse {
  public static final String SERIALIZED_NAME_COUNTRY_CODE = "countryCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  @javax.annotation.Nullable
  private String countryCode;

  public static final String SERIALIZED_NAME_VAT_NUMBER = "vatNumber";
  @SerializedName(SERIALIZED_NAME_VAT_NUMBER)
  @javax.annotation.Nullable
  private String vatNumber;

  public static final String SERIALIZED_NAME_REQUEST_DATE = "requestDate";
  @SerializedName(SERIALIZED_NAME_REQUEST_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime requestDate;

  public static final String SERIALIZED_NAME_VALID = "valid";
  @SerializedName(SERIALIZED_NAME_VALID)
  @javax.annotation.Nullable
  private Boolean valid;

  public static final String SERIALIZED_NAME_REQUEST_IDENTIFIER = "requestIdentifier";
  @SerializedName(SERIALIZED_NAME_REQUEST_IDENTIFIER)
  @javax.annotation.Nullable
  private String requestIdentifier;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  @javax.annotation.Nullable
  private String address;

  public static final String SERIALIZED_NAME_TRADER_NAME = "traderName";
  @SerializedName(SERIALIZED_NAME_TRADER_NAME)
  @javax.annotation.Nullable
  private String traderName;

  public static final String SERIALIZED_NAME_TRADER_STREET = "traderStreet";
  @SerializedName(SERIALIZED_NAME_TRADER_STREET)
  @javax.annotation.Nullable
  private String traderStreet;

  public static final String SERIALIZED_NAME_TRADER_POSTAL_CODE = "traderPostalCode";
  @SerializedName(SERIALIZED_NAME_TRADER_POSTAL_CODE)
  @javax.annotation.Nullable
  private String traderPostalCode;

  public static final String SERIALIZED_NAME_TRADER_CITY = "traderCity";
  @SerializedName(SERIALIZED_NAME_TRADER_CITY)
  @javax.annotation.Nullable
  private String traderCity;

  public static final String SERIALIZED_NAME_TRADER_COMPANY_TYPE = "traderCompanyType";
  @SerializedName(SERIALIZED_NAME_TRADER_COMPANY_TYPE)
  @javax.annotation.Nullable
  private String traderCompanyType;

  public static final String SERIALIZED_NAME_TRADER_NAME_MATCH = "traderNameMatch";
  @SerializedName(SERIALIZED_NAME_TRADER_NAME_MATCH)
  @javax.annotation.Nullable
  private Match traderNameMatch;

  public static final String SERIALIZED_NAME_TRADER_STREET_MATCH = "traderStreetMatch";
  @SerializedName(SERIALIZED_NAME_TRADER_STREET_MATCH)
  @javax.annotation.Nullable
  private Match traderStreetMatch;

  public static final String SERIALIZED_NAME_TRADER_POSTAL_CODE_MATCH = "traderPostalCodeMatch";
  @SerializedName(SERIALIZED_NAME_TRADER_POSTAL_CODE_MATCH)
  @javax.annotation.Nullable
  private Match traderPostalCodeMatch;

  public static final String SERIALIZED_NAME_TRADER_CITY_MATCH = "traderCityMatch";
  @SerializedName(SERIALIZED_NAME_TRADER_CITY_MATCH)
  @javax.annotation.Nullable
  private Match traderCityMatch;

  public static final String SERIALIZED_NAME_TRADER_COMPANY_TYPE_MATCH = "traderCompanyTypeMatch";
  @SerializedName(SERIALIZED_NAME_TRADER_COMPANY_TYPE_MATCH)
  @javax.annotation.Nullable
  private Match traderCompanyTypeMatch;

  public CheckVatResponse() {
  }

  public CheckVatResponse countryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * Get countryCode
   * @return countryCode
   */
  @javax.annotation.Nullable
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
  }


  public CheckVatResponse vatNumber(@javax.annotation.Nullable String vatNumber) {
    this.vatNumber = vatNumber;
    return this;
  }

  /**
   * Get vatNumber
   * @return vatNumber
   */
  @javax.annotation.Nullable
  public String getVatNumber() {
    return vatNumber;
  }

  public void setVatNumber(@javax.annotation.Nullable String vatNumber) {
    this.vatNumber = vatNumber;
  }


  public CheckVatResponse requestDate(@javax.annotation.Nullable OffsetDateTime requestDate) {
    this.requestDate = requestDate;
    return this;
  }

  /**
   * Get requestDate
   * @return requestDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getRequestDate() {
    return requestDate;
  }

  public void setRequestDate(@javax.annotation.Nullable OffsetDateTime requestDate) {
    this.requestDate = requestDate;
  }


  public CheckVatResponse valid(@javax.annotation.Nullable Boolean valid) {
    this.valid = valid;
    return this;
  }

  /**
   * Get valid
   * @return valid
   */
  @javax.annotation.Nullable
  public Boolean getValid() {
    return valid;
  }

  public void setValid(@javax.annotation.Nullable Boolean valid) {
    this.valid = valid;
  }


  public CheckVatResponse requestIdentifier(@javax.annotation.Nullable String requestIdentifier) {
    this.requestIdentifier = requestIdentifier;
    return this;
  }

  /**
   * Get requestIdentifier
   * @return requestIdentifier
   */
  @javax.annotation.Nullable
  public String getRequestIdentifier() {
    return requestIdentifier;
  }

  public void setRequestIdentifier(@javax.annotation.Nullable String requestIdentifier) {
    this.requestIdentifier = requestIdentifier;
  }


  public CheckVatResponse name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public CheckVatResponse address(@javax.annotation.Nullable String address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  public String getAddress() {
    return address;
  }

  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }


  public CheckVatResponse traderName(@javax.annotation.Nullable String traderName) {
    this.traderName = traderName;
    return this;
  }

  /**
   * Get traderName
   * @return traderName
   */
  @javax.annotation.Nullable
  public String getTraderName() {
    return traderName;
  }

  public void setTraderName(@javax.annotation.Nullable String traderName) {
    this.traderName = traderName;
  }


  public CheckVatResponse traderStreet(@javax.annotation.Nullable String traderStreet) {
    this.traderStreet = traderStreet;
    return this;
  }

  /**
   * Get traderStreet
   * @return traderStreet
   */
  @javax.annotation.Nullable
  public String getTraderStreet() {
    return traderStreet;
  }

  public void setTraderStreet(@javax.annotation.Nullable String traderStreet) {
    this.traderStreet = traderStreet;
  }


  public CheckVatResponse traderPostalCode(@javax.annotation.Nullable String traderPostalCode) {
    this.traderPostalCode = traderPostalCode;
    return this;
  }

  /**
   * Get traderPostalCode
   * @return traderPostalCode
   */
  @javax.annotation.Nullable
  public String getTraderPostalCode() {
    return traderPostalCode;
  }

  public void setTraderPostalCode(@javax.annotation.Nullable String traderPostalCode) {
    this.traderPostalCode = traderPostalCode;
  }


  public CheckVatResponse traderCity(@javax.annotation.Nullable String traderCity) {
    this.traderCity = traderCity;
    return this;
  }

  /**
   * Get traderCity
   * @return traderCity
   */
  @javax.annotation.Nullable
  public String getTraderCity() {
    return traderCity;
  }

  public void setTraderCity(@javax.annotation.Nullable String traderCity) {
    this.traderCity = traderCity;
  }


  public CheckVatResponse traderCompanyType(@javax.annotation.Nullable String traderCompanyType) {
    this.traderCompanyType = traderCompanyType;
    return this;
  }

  /**
   * Get traderCompanyType
   * @return traderCompanyType
   */
  @javax.annotation.Nullable
  public String getTraderCompanyType() {
    return traderCompanyType;
  }

  public void setTraderCompanyType(@javax.annotation.Nullable String traderCompanyType) {
    this.traderCompanyType = traderCompanyType;
  }


  public CheckVatResponse traderNameMatch(@javax.annotation.Nullable Match traderNameMatch) {
    this.traderNameMatch = traderNameMatch;
    return this;
  }

  /**
   * Get traderNameMatch
   * @return traderNameMatch
   */
  @javax.annotation.Nullable
  public Match getTraderNameMatch() {
    return traderNameMatch;
  }

  public void setTraderNameMatch(@javax.annotation.Nullable Match traderNameMatch) {
    this.traderNameMatch = traderNameMatch;
  }


  public CheckVatResponse traderStreetMatch(@javax.annotation.Nullable Match traderStreetMatch) {
    this.traderStreetMatch = traderStreetMatch;
    return this;
  }

  /**
   * Get traderStreetMatch
   * @return traderStreetMatch
   */
  @javax.annotation.Nullable
  public Match getTraderStreetMatch() {
    return traderStreetMatch;
  }

  public void setTraderStreetMatch(@javax.annotation.Nullable Match traderStreetMatch) {
    this.traderStreetMatch = traderStreetMatch;
  }


  public CheckVatResponse traderPostalCodeMatch(@javax.annotation.Nullable Match traderPostalCodeMatch) {
    this.traderPostalCodeMatch = traderPostalCodeMatch;
    return this;
  }

  /**
   * Get traderPostalCodeMatch
   * @return traderPostalCodeMatch
   */
  @javax.annotation.Nullable
  public Match getTraderPostalCodeMatch() {
    return traderPostalCodeMatch;
  }

  public void setTraderPostalCodeMatch(@javax.annotation.Nullable Match traderPostalCodeMatch) {
    this.traderPostalCodeMatch = traderPostalCodeMatch;
  }


  public CheckVatResponse traderCityMatch(@javax.annotation.Nullable Match traderCityMatch) {
    this.traderCityMatch = traderCityMatch;
    return this;
  }

  /**
   * Get traderCityMatch
   * @return traderCityMatch
   */
  @javax.annotation.Nullable
  public Match getTraderCityMatch() {
    return traderCityMatch;
  }

  public void setTraderCityMatch(@javax.annotation.Nullable Match traderCityMatch) {
    this.traderCityMatch = traderCityMatch;
  }


  public CheckVatResponse traderCompanyTypeMatch(@javax.annotation.Nullable Match traderCompanyTypeMatch) {
    this.traderCompanyTypeMatch = traderCompanyTypeMatch;
    return this;
  }

  /**
   * Get traderCompanyTypeMatch
   * @return traderCompanyTypeMatch
   */
  @javax.annotation.Nullable
  public Match getTraderCompanyTypeMatch() {
    return traderCompanyTypeMatch;
  }

  public void setTraderCompanyTypeMatch(@javax.annotation.Nullable Match traderCompanyTypeMatch) {
    this.traderCompanyTypeMatch = traderCompanyTypeMatch;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckVatResponse checkVatResponse = (CheckVatResponse) o;
    return Objects.equals(this.countryCode, checkVatResponse.countryCode) &&
        Objects.equals(this.vatNumber, checkVatResponse.vatNumber) &&
        Objects.equals(this.requestDate, checkVatResponse.requestDate) &&
        Objects.equals(this.valid, checkVatResponse.valid) &&
        Objects.equals(this.requestIdentifier, checkVatResponse.requestIdentifier) &&
        Objects.equals(this.name, checkVatResponse.name) &&
        Objects.equals(this.address, checkVatResponse.address) &&
        Objects.equals(this.traderName, checkVatResponse.traderName) &&
        Objects.equals(this.traderStreet, checkVatResponse.traderStreet) &&
        Objects.equals(this.traderPostalCode, checkVatResponse.traderPostalCode) &&
        Objects.equals(this.traderCity, checkVatResponse.traderCity) &&
        Objects.equals(this.traderCompanyType, checkVatResponse.traderCompanyType) &&
        Objects.equals(this.traderNameMatch, checkVatResponse.traderNameMatch) &&
        Objects.equals(this.traderStreetMatch, checkVatResponse.traderStreetMatch) &&
        Objects.equals(this.traderPostalCodeMatch, checkVatResponse.traderPostalCodeMatch) &&
        Objects.equals(this.traderCityMatch, checkVatResponse.traderCityMatch) &&
        Objects.equals(this.traderCompanyTypeMatch, checkVatResponse.traderCompanyTypeMatch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, vatNumber, requestDate, valid, requestIdentifier, name, address, traderName, traderStreet, traderPostalCode, traderCity, traderCompanyType, traderNameMatch, traderStreetMatch, traderPostalCodeMatch, traderCityMatch, traderCompanyTypeMatch);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckVatResponse {\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    vatNumber: ").append(toIndentedString(vatNumber)).append("\n");
    sb.append("    requestDate: ").append(toIndentedString(requestDate)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    requestIdentifier: ").append(toIndentedString(requestIdentifier)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    traderName: ").append(toIndentedString(traderName)).append("\n");
    sb.append("    traderStreet: ").append(toIndentedString(traderStreet)).append("\n");
    sb.append("    traderPostalCode: ").append(toIndentedString(traderPostalCode)).append("\n");
    sb.append("    traderCity: ").append(toIndentedString(traderCity)).append("\n");
    sb.append("    traderCompanyType: ").append(toIndentedString(traderCompanyType)).append("\n");
    sb.append("    traderNameMatch: ").append(toIndentedString(traderNameMatch)).append("\n");
    sb.append("    traderStreetMatch: ").append(toIndentedString(traderStreetMatch)).append("\n");
    sb.append("    traderPostalCodeMatch: ").append(toIndentedString(traderPostalCodeMatch)).append("\n");
    sb.append("    traderCityMatch: ").append(toIndentedString(traderCityMatch)).append("\n");
    sb.append("    traderCompanyTypeMatch: ").append(toIndentedString(traderCompanyTypeMatch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("countryCode");
    openapiFields.add("vatNumber");
    openapiFields.add("requestDate");
    openapiFields.add("valid");
    openapiFields.add("requestIdentifier");
    openapiFields.add("name");
    openapiFields.add("address");
    openapiFields.add("traderName");
    openapiFields.add("traderStreet");
    openapiFields.add("traderPostalCode");
    openapiFields.add("traderCity");
    openapiFields.add("traderCompanyType");
    openapiFields.add("traderNameMatch");
    openapiFields.add("traderStreetMatch");
    openapiFields.add("traderPostalCodeMatch");
    openapiFields.add("traderCityMatch");
    openapiFields.add("traderCompanyTypeMatch");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CheckVatResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CheckVatResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CheckVatResponse is not found in the empty JSON string", CheckVatResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CheckVatResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CheckVatResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("countryCode") != null && !jsonObj.get("countryCode").isJsonNull()) && !jsonObj.get("countryCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `countryCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("countryCode").toString()));
      }
      if ((jsonObj.get("vatNumber") != null && !jsonObj.get("vatNumber").isJsonNull()) && !jsonObj.get("vatNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vatNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vatNumber").toString()));
      }
      if ((jsonObj.get("requestIdentifier") != null && !jsonObj.get("requestIdentifier").isJsonNull()) && !jsonObj.get("requestIdentifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requestIdentifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requestIdentifier").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) && !jsonObj.get("address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address").toString()));
      }
      if ((jsonObj.get("traderName") != null && !jsonObj.get("traderName").isJsonNull()) && !jsonObj.get("traderName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traderName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traderName").toString()));
      }
      if ((jsonObj.get("traderStreet") != null && !jsonObj.get("traderStreet").isJsonNull()) && !jsonObj.get("traderStreet").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traderStreet` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traderStreet").toString()));
      }
      if ((jsonObj.get("traderPostalCode") != null && !jsonObj.get("traderPostalCode").isJsonNull()) && !jsonObj.get("traderPostalCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traderPostalCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traderPostalCode").toString()));
      }
      if ((jsonObj.get("traderCity") != null && !jsonObj.get("traderCity").isJsonNull()) && !jsonObj.get("traderCity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traderCity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traderCity").toString()));
      }
      if ((jsonObj.get("traderCompanyType") != null && !jsonObj.get("traderCompanyType").isJsonNull()) && !jsonObj.get("traderCompanyType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traderCompanyType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traderCompanyType").toString()));
      }
      // validate the optional field `traderNameMatch`
      if (jsonObj.get("traderNameMatch") != null && !jsonObj.get("traderNameMatch").isJsonNull()) {
        Match.validateJsonElement(jsonObj.get("traderNameMatch"));
      }
      // validate the optional field `traderStreetMatch`
      if (jsonObj.get("traderStreetMatch") != null && !jsonObj.get("traderStreetMatch").isJsonNull()) {
        Match.validateJsonElement(jsonObj.get("traderStreetMatch"));
      }
      // validate the optional field `traderPostalCodeMatch`
      if (jsonObj.get("traderPostalCodeMatch") != null && !jsonObj.get("traderPostalCodeMatch").isJsonNull()) {
        Match.validateJsonElement(jsonObj.get("traderPostalCodeMatch"));
      }
      // validate the optional field `traderCityMatch`
      if (jsonObj.get("traderCityMatch") != null && !jsonObj.get("traderCityMatch").isJsonNull()) {
        Match.validateJsonElement(jsonObj.get("traderCityMatch"));
      }
      // validate the optional field `traderCompanyTypeMatch`
      if (jsonObj.get("traderCompanyTypeMatch") != null && !jsonObj.get("traderCompanyTypeMatch").isJsonNull()) {
        Match.validateJsonElement(jsonObj.get("traderCompanyTypeMatch"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CheckVatResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CheckVatResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CheckVatResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CheckVatResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CheckVatResponse>() {
           @Override
           public void write(JsonWriter out, CheckVatResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CheckVatResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CheckVatResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CheckVatResponse
   * @throws IOException if the JSON string is invalid with respect to CheckVatResponse
   */
  public static CheckVatResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CheckVatResponse.class);
  }

  /**
   * Convert an instance of CheckVatResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

