/*
 * Vies on-the-Web Endpoint
 * This is the contract for Vies on-the-Web endpoints. The checkVat service supports exact and approximate matching at the same time. In order to retrieve the requestIdentifier, the information about requesterMemberStateCode and requesterNumber have to be provided.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.vies.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import pl.wtx.vies.api.client.model.ErrorWrapper;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.vies.api.client.invoker.JSON;

/**
 * CommonResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CommonResponse {
  public static final String SERIALIZED_NAME_ACTION_SUCCEED = "actionSucceed";
  @SerializedName(SERIALIZED_NAME_ACTION_SUCCEED)
  @javax.annotation.Nullable
  private Boolean actionSucceed;

  public static final String SERIALIZED_NAME_ERROR_WRAPPERS = "errorWrappers";
  @SerializedName(SERIALIZED_NAME_ERROR_WRAPPERS)
  @javax.annotation.Nullable
  private List<ErrorWrapper> errorWrappers = new ArrayList<>();

  public CommonResponse() {
  }

  public CommonResponse actionSucceed(@javax.annotation.Nullable Boolean actionSucceed) {
    this.actionSucceed = actionSucceed;
    return this;
  }

  /**
   * Indicate if the action succeed or not
   * @return actionSucceed
   */
  @javax.annotation.Nullable
  public Boolean getActionSucceed() {
    return actionSucceed;
  }

  public void setActionSucceed(@javax.annotation.Nullable Boolean actionSucceed) {
    this.actionSucceed = actionSucceed;
  }


  public CommonResponse errorWrappers(@javax.annotation.Nullable List<ErrorWrapper> errorWrappers) {
    this.errorWrappers = errorWrappers;
    return this;
  }

  public CommonResponse addErrorWrappersItem(ErrorWrapper errorWrappersItem) {
    if (this.errorWrappers == null) {
      this.errorWrappers = new ArrayList<>();
    }
    this.errorWrappers.add(errorWrappersItem);
    return this;
  }

  /**
   * Indicate the cause of the error when actionSucceed is false.
   * @return errorWrappers
   */
  @javax.annotation.Nullable
  public List<ErrorWrapper> getErrorWrappers() {
    return errorWrappers;
  }

  public void setErrorWrappers(@javax.annotation.Nullable List<ErrorWrapper> errorWrappers) {
    this.errorWrappers = errorWrappers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommonResponse commonResponse = (CommonResponse) o;
    return Objects.equals(this.actionSucceed, commonResponse.actionSucceed) &&
        Objects.equals(this.errorWrappers, commonResponse.errorWrappers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionSucceed, errorWrappers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommonResponse {\n");
    sb.append("    actionSucceed: ").append(toIndentedString(actionSucceed)).append("\n");
    sb.append("    errorWrappers: ").append(toIndentedString(errorWrappers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("actionSucceed");
    openapiFields.add("errorWrappers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CommonResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CommonResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CommonResponse is not found in the empty JSON string", CommonResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CommonResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CommonResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("errorWrappers") != null && !jsonObj.get("errorWrappers").isJsonNull()) {
        JsonArray jsonArrayerrorWrappers = jsonObj.getAsJsonArray("errorWrappers");
        if (jsonArrayerrorWrappers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("errorWrappers").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `errorWrappers` to be an array in the JSON string but got `%s`", jsonObj.get("errorWrappers").toString()));
          }

          // validate the optional field `errorWrappers` (array)
          for (int i = 0; i < jsonArrayerrorWrappers.size(); i++) {
            ErrorWrapper.validateJsonElement(jsonArrayerrorWrappers.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CommonResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CommonResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CommonResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CommonResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CommonResponse>() {
           @Override
           public void write(JsonWriter out, CommonResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CommonResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CommonResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CommonResponse
   * @throws IOException if the JSON string is invalid with respect to CommonResponse
   */
  public static CommonResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CommonResponse.class);
  }

  /**
   * Convert an instance of CommonResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

