/*
 * Vies on-the-Web Endpoint
 * This is the contract for Vies on-the-Web endpoints. The checkVat service supports exact and approximate matching at the same time. In order to retrieve the requestIdentifier, the information about requesterMemberStateCode and requesterNumber have to be provided.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.vies.api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Match
 */
@JsonAdapter(Match.Adapter.class)
public enum Match {
  
  VALID("VALID"),
  
  INVALID("INVALID"),
  
  NOT_PROCESSED("NOT_PROCESSED");

  private String value;

  Match(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Match fromValue(String value) {
    for (Match b : Match.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Match> {
    @Override
    public void write(final JsonWriter jsonWriter, final Match enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Match read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Match.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    Match.fromValue(value);
  }
}

