/*
 * Vies on-the-Web Endpoint
 * This is the contract for Vies on-the-Web endpoints. The checkVat service supports exact and approximate matching at the same time. In order to retrieve the requestIdentifier, the information about requesterMemberStateCode and requesterNumber have to be provided.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.vies.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import pl.wtx.vies.api.client.model.CountryStatus;
import pl.wtx.vies.api.client.model.StatusInformationResponseVow;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.vies.api.client.invoker.JSON;

/**
 * StatusInformationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class StatusInformationResponse {
  public static final String SERIALIZED_NAME_VOW = "vow";
  @SerializedName(SERIALIZED_NAME_VOW)
  @javax.annotation.Nullable
  private StatusInformationResponseVow vow;

  public static final String SERIALIZED_NAME_COUNTRIES = "countries";
  @SerializedName(SERIALIZED_NAME_COUNTRIES)
  @javax.annotation.Nullable
  private List<CountryStatus> countries = new ArrayList<>();

  public StatusInformationResponse() {
  }

  public StatusInformationResponse vow(@javax.annotation.Nullable StatusInformationResponseVow vow) {
    this.vow = vow;
    return this;
  }

  /**
   * Get vow
   * @return vow
   */
  @javax.annotation.Nullable
  public StatusInformationResponseVow getVow() {
    return vow;
  }

  public void setVow(@javax.annotation.Nullable StatusInformationResponseVow vow) {
    this.vow = vow;
  }


  public StatusInformationResponse countries(@javax.annotation.Nullable List<CountryStatus> countries) {
    this.countries = countries;
    return this;
  }

  public StatusInformationResponse addCountriesItem(CountryStatus countriesItem) {
    if (this.countries == null) {
      this.countries = new ArrayList<>();
    }
    this.countries.add(countriesItem);
    return this;
  }

  /**
   * Get countries
   * @return countries
   */
  @javax.annotation.Nullable
  public List<CountryStatus> getCountries() {
    return countries;
  }

  public void setCountries(@javax.annotation.Nullable List<CountryStatus> countries) {
    this.countries = countries;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusInformationResponse statusInformationResponse = (StatusInformationResponse) o;
    return Objects.equals(this.vow, statusInformationResponse.vow) &&
        Objects.equals(this.countries, statusInformationResponse.countries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vow, countries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusInformationResponse {\n");
    sb.append("    vow: ").append(toIndentedString(vow)).append("\n");
    sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("vow");
    openapiFields.add("countries");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StatusInformationResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StatusInformationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StatusInformationResponse is not found in the empty JSON string", StatusInformationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StatusInformationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `StatusInformationResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `vow`
      if (jsonObj.get("vow") != null && !jsonObj.get("vow").isJsonNull()) {
        StatusInformationResponseVow.validateJsonElement(jsonObj.get("vow"));
      }
      if (jsonObj.get("countries") != null && !jsonObj.get("countries").isJsonNull()) {
        JsonArray jsonArraycountries = jsonObj.getAsJsonArray("countries");
        if (jsonArraycountries != null) {
          // ensure the json data is an array
          if (!jsonObj.get("countries").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `countries` to be an array in the JSON string but got `%s`", jsonObj.get("countries").toString()));
          }

          // validate the optional field `countries` (array)
          for (int i = 0; i < jsonArraycountries.size(); i++) {
            CountryStatus.validateJsonElement(jsonArraycountries.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatusInformationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatusInformationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatusInformationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatusInformationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<StatusInformationResponse>() {
           @Override
           public void write(JsonWriter out, StatusInformationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StatusInformationResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StatusInformationResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StatusInformationResponse
   * @throws IOException if the JSON string is invalid with respect to StatusInformationResponse
   */
  public static StatusInformationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatusInformationResponse.class);
  }

  /**
   * Convert an instance of StatusInformationResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

